# configurando puerto y direccion de escucha para despliegue en contenedores
server.address=0.0.0.0
server.port=${PORT:8080}
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# configurando conexiones a la base de datos para despliegue en contenedores
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=60000

# email para el administrador inicial
app.bootstrap.admin.email=${INITIAL_ADMIN_EMAIL}
app.mail.provider=brevo
app.mail.from=${MAIL_FROM}

# Logs
logging.level.com.restaurante=INFO

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
