
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS restaurante;
SET search_path TO restaurante, public;
SET TIME ZONE 'UTC';

CREATE TABLE restaurantes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                  VARCHAR(150) NOT NULL,
    nombre_comercial        VARCHAR(150) NULL,
    identificacion_fiscal   VARCHAR(40) NULL,
    direccion               VARCHAR(255) NULL,
    telefono                VARCHAR(25) NULL,
    correo                  VARCHAR(150) NULL,
    moneda                  CHAR(3) NOT NULL DEFAULT 'GTQ',
    zona_horaria            VARCHAR(60) NOT NULL DEFAULT 'America/Guatemala',
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_restaurante_identificacion_fiscal
        UNIQUE (identificacion_fiscal)
);

CREATE TABLE usuarios (
    id                  BIGINT PRIMARY KEY,
    restaurante_id      BIGINT NOT NULL,
    codigo_empleado     VARCHAR(30) NOT NULL,
    nombres             VARCHAR(100) NOT NULL,
    apellidos           VARCHAR(100) NOT NULL,
    telefono            VARCHAR(25) NULL,
    fecha_contratacion  DATE NULL,
    ultimo_acceso_en    TIMESTAMPTZ(6) NULL,
    creado_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuarios_restaurante_codigo
        UNIQUE (restaurante_id, codigo_empleado),
    CONSTRAINT fk_usuarios_cuenta
        FOREIGN KEY (id) REFERENCES public.app_users(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_usuarios_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_usuarios_restaurante
    ON usuarios (restaurante_id);


CREATE TABLE configuraciones_restaurante (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id              BIGINT NOT NULL,
    porcentaje_impuesto         DECIMAL(7,4) NOT NULL DEFAULT 12.0000,
    porcentaje_propina          DECIMAL(7,4) NOT NULL DEFAULT 10.0000,
    propina_editable            BOOLEAN NOT NULL DEFAULT TRUE,
    puntos_por_moneda           DECIMAL(12,4) NOT NULL DEFAULT 1.0000,
    valor_monetario_punto       DECIMAL(12,4) NOT NULL DEFAULT 0.0100,
    duracion_reserva_minutos    SMALLINT NOT NULL DEFAULT 120,
    tolerancia_reserva_minutos  SMALLINT NOT NULL DEFAULT 15,
    vigente_desde               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vigente_hasta               TIMESTAMPTZ(6) NULL,
    estado                      VARCHAR(15) NOT NULL DEFAULT 'VIGENTE',
    creado_por_id               BIGINT NULL,
    creado_en                   TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_config_porcentajes CHECK (
        porcentaje_impuesto BETWEEN 0 AND 100
        AND porcentaje_propina BETWEEN 0 AND 100
    ),
    CONSTRAINT chk_config_fidelizacion CHECK (
        puntos_por_moneda >= 0 AND valor_monetario_punto >= 0
    ),
    CONSTRAINT chk_config_reserva CHECK (
        duracion_reserva_minutos > 0
        AND tolerancia_reserva_minutos >= 0
    ),
    CONSTRAINT chk_config_estado CHECK (
        estado IN ('VIGENTE', 'HISTORICA')
    ),
    CONSTRAINT chk_config_fechas CHECK (
        (estado = 'VIGENTE' AND vigente_hasta IS NULL)
        OR (estado = 'HISTORICA'
            AND vigente_hasta IS NOT NULL
            AND vigente_hasta > vigente_desde)
    ),
    CONSTRAINT fk_config_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_config_creado_por
        FOREIGN KEY (creado_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_configuracion_vigente
    ON configuraciones_restaurante (restaurante_id)
    WHERE estado = 'VIGENTE';

CREATE TABLE auditoria (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id      BIGINT NOT NULL,
    usuario_id          BIGINT NULL,
    accion              VARCHAR(60) NOT NULL,
    entidad             VARCHAR(80) NOT NULL,
    entidad_id          VARCHAR(80) NOT NULL,
    valores_anteriores  JSONB NULL,
    valores_nuevos      JSONB NULL,
    motivo              VARCHAR(500) NULL,
    direccion_ip        VARCHAR(45) NULL,
    creado_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auditoria_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE INDEX idx_auditoria_entidad
    ON auditoria (entidad, entidad_id, creado_en);
CREATE INDEX idx_auditoria_usuario_fecha
    ON auditoria (usuario_id, creado_en);

CREATE TABLE notificaciones (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id          BIGINT NOT NULL,
    destinatario_id         BIGINT NULL,
    rol_destinatario_id     BIGINT NULL,
    tipo                    VARCHAR(40) NOT NULL,
    titulo                  VARCHAR(150) NOT NULL,
    mensaje                 VARCHAR(500) NOT NULL,
    entidad                 VARCHAR(80) NULL,
    entidad_id              VARCHAR(80) NULL,
    prioridad               VARCHAR(10) NOT NULL DEFAULT 'MEDIA',
    leida                   BOOLEAN NOT NULL DEFAULT FALSE,
    leida_en                TIMESTAMPTZ(6) NULL,
    creada_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_notificacion_prioridad CHECK (
        prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')
    ),
    CONSTRAINT chk_notificacion_destino CHECK (
        destinatario_id IS NOT NULL OR rol_destinatario_id IS NOT NULL
    ),
    CONSTRAINT chk_notificacion_lectura CHECK (
        (leida = FALSE AND leida_en IS NULL)
        OR (leida = TRUE AND leida_en IS NOT NULL)
    ),
    CONSTRAINT fk_notificaciones_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_notificaciones_destinatario
        FOREIGN KEY (destinatario_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_notificaciones_rol
        FOREIGN KEY (rol_destinatario_id) REFERENCES public.roles(id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE INDEX idx_notificaciones_pendientes_usuario
    ON notificaciones (destinatario_id, leida, creada_en);
CREATE INDEX idx_notificaciones_pendientes_rol
    ON notificaciones (rol_destinatario_id, leida, creada_en);


CREATE TABLE unidades_medida (
    id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20) NOT NULL,
    nombre          VARCHAR(60) NOT NULL,
    abreviatura     VARCHAR(10) NOT NULL,
    dimension       VARCHAR(15) NOT NULL,
    factor_a_base   DECIMAL(18,6) NOT NULL,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_unidades_codigo UNIQUE (codigo),
    CONSTRAINT chk_unidad_dimension CHECK (
        dimension IN ('MASA', 'VOLUMEN', 'CONTEO')
    ),
    CONSTRAINT chk_unidad_factor CHECK (factor_a_base > 0)
);

CREATE TABLE categorias_insumo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT NOT NULL,
    nombre          VARCHAR(80) NOT NULL,
    descripcion     VARCHAR(255) NULL,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_categoria_insumo_nombre
        UNIQUE (restaurante_id, nombre),
    CONSTRAINT fk_categoria_insumo_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE insumos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id          BIGINT NOT NULL,
    categoria_insumo_id     BIGINT NOT NULL,
    unidad_stock_id         SMALLINT NOT NULL,
    codigo                  VARCHAR(30) NOT NULL,
    nombre                  VARCHAR(120) NOT NULL,
    descripcion             VARCHAR(255) NULL,
    costo_unitario_actual   DECIMAL(14,4) NOT NULL DEFAULT 0,
    stock_actual            DECIMAL(18,4) NOT NULL DEFAULT 0,
    stock_minimo            DECIMAL(18,4) NOT NULL DEFAULT 0,
    stock_maximo            DECIMAL(18,4) NULL,
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_insumo_codigo UNIQUE (restaurante_id, codigo),
    CONSTRAINT uq_insumo_nombre UNIQUE (restaurante_id, nombre),
    CONSTRAINT chk_insumo_valores CHECK (
        costo_unitario_actual >= 0
        AND stock_actual >= 0
        AND stock_minimo >= 0
        AND (stock_maximo IS NULL OR stock_maximo >= stock_minimo)
    ),
    CONSTRAINT fk_insumo_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_insumo_categoria
        FOREIGN KEY (categoria_insumo_id) REFERENCES categorias_insumo(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_insumo_unidad
        FOREIGN KEY (unidad_stock_id) REFERENCES unidades_medida(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_insumos_stock_bajo
    ON insumos (restaurante_id, activo, stock_actual, stock_minimo);

CREATE TABLE historial_costos_insumo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id           BIGINT NOT NULL,
    costo_anterior      DECIMAL(14,4) NOT NULL,
    costo_nuevo         DECIMAL(14,4) NOT NULL,
    motivo              VARCHAR(255) NOT NULL,
    usuario_id          BIGINT NULL,
    vigente_desde       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_historial_costo CHECK (
        costo_anterior >= 0 AND costo_nuevo >= 0
    ),
    CONSTRAINT fk_historial_costo_insumo
        FOREIGN KEY (insumo_id) REFERENCES insumos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_historial_costo_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE INDEX idx_historial_costo_insumo_fecha
    ON historial_costos_insumo (insumo_id, vigente_desde);


CREATE INDEX idx_fk_config_creado_por
    ON configuraciones_restaurante (creado_por_id);
CREATE INDEX idx_fk_auditoria_restaurante
    ON auditoria (restaurante_id);
CREATE INDEX idx_fk_notificacion_restaurante
    ON notificaciones (restaurante_id);
CREATE INDEX idx_fk_insumo_categoria
    ON insumos (categoria_insumo_id);
CREATE INDEX idx_fk_insumo_unidad
    ON insumos (unidad_stock_id);
CREATE INDEX idx_fk_historial_costo_usuario
    ON historial_costos_insumo (usuario_id);
