
SET search_path TO restaurante, public;
SET TIME ZONE 'UTC';

CREATE TABLE categorias_platillo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT NOT NULL,
    codigo          VARCHAR(30) NOT NULL,
    nombre          VARCHAR(80) NOT NULL,
    descripcion     VARCHAR(255) NULL,
    orden_visual    SMALLINT NOT NULL DEFAULT 0,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_categoria_platillo_codigo
        UNIQUE (restaurante_id, codigo),
    CONSTRAINT uq_categoria_platillo_nombre
        UNIQUE (restaurante_id, nombre),
    CONSTRAINT fk_categoria_platillo_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE platillos (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id              BIGINT NOT NULL,
    categoria_platillo_id       BIGINT NOT NULL,
    codigo                      VARCHAR(30) NOT NULL,
    nombre                      VARCHAR(120) NOT NULL,
    descripcion                 VARCHAR(500) NULL,
    precio_venta                DECIMAL(12,2) NOT NULL,
    imagen_url                  VARCHAR(500) NULL,
    tiempo_preparacion_minutos  SMALLINT NOT NULL,
    disponible_manual           BOOLEAN NOT NULL DEFAULT TRUE,
    activo                      BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en                   TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en              TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_platillo_codigo UNIQUE (restaurante_id, codigo),
    CONSTRAINT uq_platillo_nombre UNIQUE (restaurante_id, nombre),
    CONSTRAINT chk_platillo_precio_tiempo CHECK (
        precio_venta >= 0 AND tiempo_preparacion_minutos > 0
    ),
    CONSTRAINT fk_platillo_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_platillo_categoria
        FOREIGN KEY (categoria_platillo_id) REFERENCES categorias_platillo(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_platillos_menu
    ON platillos (restaurante_id, categoria_platillo_id, activo, disponible_manual);


CREATE TABLE receta_versiones (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platillo_id             BIGINT NOT NULL,
    numero_version          INTEGER NOT NULL,
    estado                  VARCHAR(15) NOT NULL DEFAULT 'BORRADOR',
    motivo_cambio           VARCHAR(500) NULL,
    vigente_desde           TIMESTAMPTZ(6) NULL,
    vigente_hasta           TIMESTAMPTZ(6) NULL,
    creado_por_id           BIGINT NULL,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_receta_version UNIQUE (platillo_id, numero_version),
    CONSTRAINT chk_receta_numero_version CHECK (numero_version > 0),
    CONSTRAINT chk_receta_version_estado CHECK (
        estado IN ('BORRADOR', 'VIGENTE', 'HISTORICA')
    ),
    CONSTRAINT chk_receta_version_fechas CHECK (
        (estado = 'BORRADOR'
            AND vigente_desde IS NULL
            AND vigente_hasta IS NULL)
        OR (estado = 'VIGENTE'
            AND vigente_desde IS NOT NULL
            AND vigente_hasta IS NULL)
        OR (estado = 'HISTORICA'
            AND vigente_desde IS NOT NULL
            AND vigente_hasta IS NOT NULL
            AND vigente_hasta > vigente_desde)
    ),
    CONSTRAINT fk_receta_version_platillo
        FOREIGN KEY (platillo_id) REFERENCES platillos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_receta_version_usuario
        FOREIGN KEY (creado_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_receta_platillo_vigente
    ON receta_versiones (platillo_id)
    WHERE estado = 'VIGENTE';

CREATE TABLE receta_detalles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receta_version_id   BIGINT NOT NULL,
    insumo_id           BIGINT NOT NULL,
    unidad_medida_id    SMALLINT NOT NULL,
    cantidad            DECIMAL(18,6) NOT NULL,
    observacion         VARCHAR(255) NULL,
    CONSTRAINT uq_receta_detalle_insumo
        UNIQUE (receta_version_id, insumo_id),
    CONSTRAINT chk_receta_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_receta_detalle_version
        FOREIGN KEY (receta_version_id) REFERENCES receta_versiones(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_receta_detalle_insumo
        FOREIGN KEY (insumo_id) REFERENCES insumos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_receta_detalle_unidad
        FOREIGN KEY (unidad_medida_id) REFERENCES unidades_medida(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE modificadores (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id          BIGINT NOT NULL,
    codigo                  VARCHAR(30) NOT NULL,
    nombre                  VARCHAR(100) NOT NULL,
    descripcion             VARCHAR(255) NULL,
    precio_adicional        DECIMAL(12,2) NOT NULL DEFAULT 0,
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_modificador_codigo UNIQUE (restaurante_id, codigo),
    CONSTRAINT uq_modificador_nombre UNIQUE (restaurante_id, nombre),
    CONSTRAINT chk_modificador_precio CHECK (precio_adicional >= 0),
    CONSTRAINT fk_modificador_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE platillo_modificadores (
    platillo_id        BIGINT NOT NULL,
    modificador_id     BIGINT NOT NULL,
    obligatorio        BOOLEAN NOT NULL DEFAULT FALSE,
    maximo_selecciones SMALLINT NOT NULL DEFAULT 1,
    orden_visual       SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (platillo_id, modificador_id),
    CONSTRAINT chk_platillo_modificador_maximo CHECK (maximo_selecciones > 0),
    CONSTRAINT fk_platillo_modificador_platillo
        FOREIGN KEY (platillo_id) REFERENCES platillos(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_platillo_modificador_modificador
        FOREIGN KEY (modificador_id) REFERENCES modificadores(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE receta_modificador_versiones (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modificador_id          BIGINT NOT NULL,
    numero_version          INTEGER NOT NULL,
    estado                  VARCHAR(15) NOT NULL DEFAULT 'BORRADOR',
    motivo_cambio           VARCHAR(500) NULL,
    vigente_desde           TIMESTAMPTZ(6) NULL,
    vigente_hasta           TIMESTAMPTZ(6) NULL,
    creado_por_id           BIGINT NULL,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_receta_mod_version
        UNIQUE (modificador_id, numero_version),
    CONSTRAINT chk_receta_mod_numero_version CHECK (numero_version > 0),
    CONSTRAINT chk_receta_mod_estado CHECK (
        estado IN ('BORRADOR', 'VIGENTE', 'HISTORICA')
    ),
    CONSTRAINT chk_receta_mod_fechas CHECK (
        (estado = 'BORRADOR'
            AND vigente_desde IS NULL
            AND vigente_hasta IS NULL)
        OR (estado = 'VIGENTE'
            AND vigente_desde IS NOT NULL
            AND vigente_hasta IS NULL)
        OR (estado = 'HISTORICA'
            AND vigente_desde IS NOT NULL
            AND vigente_hasta IS NOT NULL
            AND vigente_hasta > vigente_desde)
    ),
    CONSTRAINT fk_receta_mod_modificador
        FOREIGN KEY (modificador_id) REFERENCES modificadores(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_receta_mod_usuario
        FOREIGN KEY (creado_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_receta_mod_vigente
    ON receta_modificador_versiones (modificador_id)
    WHERE estado = 'VIGENTE';


CREATE TABLE receta_modificador_detalles (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receta_modificador_version_id   BIGINT NOT NULL,
    insumo_id                       BIGINT NOT NULL,
    unidad_medida_id                SMALLINT NOT NULL,
    tipo_ajuste                     VARCHAR(10) NOT NULL,
    cantidad                        DECIMAL(18,6) NOT NULL,
    observacion                     VARCHAR(255) NULL,
    CONSTRAINT uq_receta_mod_detalle
        UNIQUE (receta_modificador_version_id, insumo_id, tipo_ajuste),
    CONSTRAINT chk_receta_mod_tipo CHECK (
        tipo_ajuste IN ('AGREGAR', 'RETIRAR')
    ),
    CONSTRAINT chk_receta_mod_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_receta_mod_detalle_version
        FOREIGN KEY (receta_modificador_version_id)
        REFERENCES receta_modificador_versiones(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_receta_mod_detalle_insumo
        FOREIGN KEY (insumo_id) REFERENCES insumos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_receta_mod_detalle_unidad
        FOREIGN KEY (unidad_medida_id) REFERENCES unidades_medida(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE combos (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id              BIGINT NOT NULL,
    codigo                      VARCHAR(30) NOT NULL,
    nombre                      VARCHAR(120) NOT NULL,
    descripcion                 VARCHAR(500) NULL,
    precio_venta                DECIMAL(12,2) NOT NULL,
    imagen_url                  VARCHAR(500) NULL,
    tiempo_preparacion_minutos  SMALLINT NOT NULL,
    disponible_manual           BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_inicio                TIMESTAMPTZ(6) NULL,
    fecha_fin                   TIMESTAMPTZ(6) NULL,
    activo                      BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en                   TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en              TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_combo_codigo UNIQUE (restaurante_id, codigo),
    CONSTRAINT uq_combo_nombre UNIQUE (restaurante_id, nombre),
    CONSTRAINT chk_combo_precio_tiempo CHECK (
        precio_venta >= 0 AND tiempo_preparacion_minutos > 0
    ),
    CONSTRAINT chk_combo_fechas CHECK (
        fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin > fecha_inicio
    ),
    CONSTRAINT fk_combo_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE combo_detalles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_id        BIGINT NOT NULL,
    platillo_id     BIGINT NOT NULL,
    cantidad        SMALLINT NOT NULL DEFAULT 1,
    orden_visual    SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_combo_platillo UNIQUE (combo_id, platillo_id),
    CONSTRAINT chk_combo_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_combo_detalle_combo
        FOREIGN KEY (combo_id) REFERENCES combos(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_combo_detalle_platillo
        FOREIGN KEY (platillo_id) REFERENCES platillos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);


CREATE TABLE zonas_mesa (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT NOT NULL,
    nombre          VARCHAR(80) NOT NULL,
    descripcion     VARCHAR(255) NULL,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_zona_mesa_nombre UNIQUE (restaurante_id, nombre),
    CONSTRAINT fk_zona_mesa_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE mesas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT NOT NULL,
    zona_mesa_id    BIGINT NOT NULL,
    numero          VARCHAR(20) NOT NULL,
    capacidad       SMALLINT NOT NULL,
    estado_actual   VARCHAR(20) NOT NULL DEFAULT 'LIBRE',
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mesa_numero UNIQUE (restaurante_id, numero),
    CONSTRAINT chk_mesa_capacidad CHECK (capacidad > 0),
    CONSTRAINT chk_mesa_estado CHECK (
        estado_actual IN ('LIBRE', 'RESERVADA', 'OCUPADA', 'CUENTA_SOLICITADA')
    ),
    CONSTRAINT fk_mesa_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_mesa_zona
        FOREIGN KEY (zona_mesa_id) REFERENCES zonas_mesa(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_mesas_panel
    ON mesas (restaurante_id, estado_actual, activo, capacidad);

CREATE TABLE clientes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id          BIGINT NOT NULL,
    nombres                 VARCHAR(120) NOT NULL,
    apellidos               VARCHAR(120) NULL,
    telefono                VARCHAR(25) NOT NULL,
    correo                  VARCHAR(150) NULL,
    saldo_puntos            BIGINT NOT NULL DEFAULT 0,
    total_visitas           INTEGER NOT NULL DEFAULT 0,
    ultima_visita_en        TIMESTAMPTZ(6) NULL,
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cliente_telefono UNIQUE (restaurante_id, telefono),
    CONSTRAINT chk_cliente_saldo_puntos CHECK (saldo_puntos >= 0),
    CONSTRAINT fk_cliente_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_clientes_frecuencia
    ON clientes (restaurante_id, total_visitas, ultima_visita_en);

CREATE UNIQUE INDEX uq_cliente_correo_ci
    ON clientes (restaurante_id, LOWER(BTRIM(correo)))
    WHERE correo IS NOT NULL;

CREATE TABLE reservas (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id          BIGINT NOT NULL,
    mesa_id                 BIGINT NOT NULL,
    cliente_id              BIGINT NULL,
    codigo_reserva          VARCHAR(30) NOT NULL,
    nombre_cliente          VARCHAR(150) NOT NULL,
    telefono_cliente        VARCHAR(25) NOT NULL,
    cantidad_personas       SMALLINT NOT NULL,
    fecha_hora_inicio       TIMESTAMPTZ(6) NOT NULL,
    fecha_hora_fin          TIMESTAMPTZ(6) NOT NULL,
    estado                  VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    notas                   VARCHAR(500) NULL,
    creada_por_id           BIGINT NULL,
    confirmada_en           TIMESTAMPTZ(6) NULL,
    llegada_en              TIMESTAMPTZ(6) NULL,
    cancelada_en            TIMESTAMPTZ(6) NULL,
    motivo_cancelacion      VARCHAR(500) NULL,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_reserva_codigo UNIQUE (restaurante_id, codigo_reserva),
    CONSTRAINT chk_reserva_personas CHECK (cantidad_personas > 0),
    CONSTRAINT chk_reserva_fechas CHECK (fecha_hora_fin > fecha_hora_inicio),
    CONSTRAINT chk_reserva_estado CHECK (
        estado IN (
            'PENDIENTE', 'CONFIRMADA', 'CLIENTE_PRESENTE',
            'ATENDIDA', 'CANCELADA', 'NO_ASISTIO'
        )
    ),
    CONSTRAINT fk_reserva_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_reserva_mesa
        FOREIGN KEY (mesa_id) REFERENCES mesas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_reserva_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_reserva_creada_por
        FOREIGN KEY (creada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE INDEX idx_reservas_mesa_horario
    ON reservas (mesa_id, fecha_hora_inicio, fecha_hora_fin, estado);
CREATE INDEX idx_reservas_proximas
    ON reservas (restaurante_id, estado, fecha_hora_inicio);
CREATE INDEX idx_reservas_telefono
    ON reservas (restaurante_id, telefono_cliente, fecha_hora_inicio);

ALTER TABLE reservas
    ADD CONSTRAINT ex_reservas_mesa_horario
    EXCLUDE USING gist (
        mesa_id WITH =,
        tstzrange(fecha_hora_inicio, fecha_hora_fin, '[)') WITH &&
    )
    WHERE (
        estado IN ('PENDIENTE', 'CONFIRMADA', 'CLIENTE_PRESENTE')
    );

CREATE TABLE lista_espera (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id      BIGINT NOT NULL,
    cliente_id          BIGINT NULL,
    nombre_cliente      VARCHAR(150) NOT NULL,
    telefono_cliente    VARCHAR(25) NOT NULL,
    cantidad_personas   SMALLINT NOT NULL,
    hora_llegada        TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado              VARCHAR(20) NOT NULL DEFAULT 'ESPERANDO',
    mesa_sugerida_id    BIGINT NULL,
    sugerida_en         TIMESTAMPTZ(6) NULL,
    notificada_en       TIMESTAMPTZ(6) NULL,
    sentada_en          TIMESTAMPTZ(6) NULL,
    retirada_en         TIMESTAMPTZ(6) NULL,
    notas               VARCHAR(500) NULL,
    registrada_por_id   BIGINT NULL,
    creado_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_espera_personas CHECK (cantidad_personas > 0),
    CONSTRAINT chk_espera_estado CHECK (
        estado IN ('ESPERANDO', 'SUGERIDA', 'NOTIFICADA', 'SENTADA', 'RETIRADA')
    ),
    CONSTRAINT fk_espera_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_espera_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_espera_mesa_sugerida
        FOREIGN KEY (mesa_sugerida_id) REFERENCES mesas(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_espera_registrada_por
        FOREIGN KEY (registrada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE INDEX idx_lista_espera_cola
    ON lista_espera (restaurante_id, estado, hora_llegada);
CREATE INDEX idx_lista_espera_capacidad
    ON lista_espera (restaurante_id, estado, cantidad_personas, hora_llegada);

CREATE UNIQUE INDEX uq_lista_espera_mesa_sugerencia_activa
    ON lista_espera (mesa_sugerida_id)
    WHERE mesa_sugerida_id IS NOT NULL
      AND estado IN ('SUGERIDA', 'NOTIFICADA');


CREATE INDEX idx_fk_platillo_categoria
    ON platillos (categoria_platillo_id);
CREATE INDEX idx_fk_receta_version_usuario
    ON receta_versiones (creado_por_id);
CREATE INDEX idx_fk_receta_detalle_insumo
    ON receta_detalles (insumo_id);
CREATE INDEX idx_fk_receta_detalle_unidad
    ON receta_detalles (unidad_medida_id);
CREATE INDEX idx_fk_platillo_mod_modificador
    ON platillo_modificadores (modificador_id);
CREATE INDEX idx_fk_receta_mod_usuario
    ON receta_modificador_versiones (creado_por_id);
CREATE INDEX idx_fk_receta_mod_detalle_insumo
    ON receta_modificador_detalles (insumo_id);
CREATE INDEX idx_fk_receta_mod_detalle_unidad
    ON receta_modificador_detalles (unidad_medida_id);
CREATE INDEX idx_fk_combo_detalle_platillo
    ON combo_detalles (platillo_id);
CREATE INDEX idx_fk_mesa_zona
    ON mesas (zona_mesa_id);
CREATE INDEX idx_fk_reserva_cliente
    ON reservas (cliente_id);
CREATE INDEX idx_fk_reserva_creada_por
    ON reservas (creada_por_id);
CREATE INDEX idx_fk_espera_cliente
    ON lista_espera (cliente_id);
CREATE INDEX idx_fk_espera_mesa_sugerida
    ON lista_espera (mesa_sugerida_id);
CREATE INDEX idx_fk_espera_registrada_por
    ON lista_espera (registrada_por_id);
