-- Cuentas, comandas, cocina, divisiones e inventario transaccional.
SET search_path TO restaurante, public;
SET TIME ZONE 'UTC';

CREATE TABLE cuentas (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id          BIGINT NOT NULL,
    mesa_id                 BIGINT NOT NULL,
    mesero_id               BIGINT NOT NULL,
    cliente_id              BIGINT NULL,
    reserva_id              BIGINT NULL,
    lista_espera_id         BIGINT NULL,
    numero_cuenta           VARCHAR(30) NOT NULL,
    cantidad_personas       SMALLINT NOT NULL DEFAULT 1,
    estado                  VARCHAR(25) NOT NULL DEFAULT 'ABIERTA',
    abierta_en              TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    solicitada_cobro_en     TIMESTAMPTZ(6) NULL,
    cerrada_en              TIMESTAMPTZ(6) NULL,
    observaciones           VARCHAR(500) NULL,
    creado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en          TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cuenta_numero UNIQUE (restaurante_id, numero_cuenta),
    CONSTRAINT uq_cuenta_reserva UNIQUE (reserva_id),
    CONSTRAINT uq_cuenta_lista_espera UNIQUE (lista_espera_id),
    CONSTRAINT chk_cuenta_personas CHECK (cantidad_personas > 0),
    CONSTRAINT chk_cuenta_origen_cliente CHECK (
        num_nonnulls(reserva_id, lista_espera_id) <= 1
    ),
    CONSTRAINT chk_cuenta_estado CHECK (
        estado IN (
            'ABIERTA', 'LISTA_COBRO', 'PARCIALMENTE_PAGADA',
            'CERRADA', 'CANCELADA', 'FUSIONADA'
        )
    ),
    CONSTRAINT chk_cuenta_fechas_estado CHECK (
        (estado IN ('ABIERTA', 'LISTA_COBRO', 'PARCIALMENTE_PAGADA')
            AND cerrada_en IS NULL)
        OR (estado IN ('CERRADA', 'CANCELADA', 'FUSIONADA')
            AND cerrada_en IS NOT NULL)
    ),
    CONSTRAINT fk_cuenta_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_cuenta_mesa
        FOREIGN KEY (mesa_id) REFERENCES mesas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_cuenta_mesero
        FOREIGN KEY (mesero_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_cuenta_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_cuenta_reserva
        FOREIGN KEY (reserva_id) REFERENCES reservas(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_cuenta_lista_espera
        FOREIGN KEY (lista_espera_id) REFERENCES lista_espera(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_cuenta_activa_mesa
    ON cuentas (mesa_id)
    WHERE estado IN ('ABIERTA', 'LISTA_COBRO', 'PARCIALMENTE_PAGADA');

CREATE INDEX idx_cuentas_mesero_estado
    ON cuentas (mesero_id, estado, abierta_en);
CREATE INDEX idx_cuentas_listas_cobro
    ON cuentas (restaurante_id, estado, solicitada_cobro_en);

-- Relaciona una cuenta con todas las mesas que mantiene ocupadas. La columna
-- cuentas.mesa_id conserva la mesa principal para compatibilidad con la API,
-- mientras esta tabla permite mantener mesas anexas durante una fusion.
CREATE TABLE cuenta_mesas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id           BIGINT NOT NULL,
    mesa_id             BIGINT NOT NULL,
    es_principal        BOOLEAN NOT NULL DEFAULT FALSE,
    origen_cuenta_id    BIGINT NULL,
    activa              BOOLEAN NOT NULL DEFAULT TRUE,
    vinculada_en        TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    desvinculada_en     TIMESTAMPTZ(6) NULL,
    CONSTRAINT uq_cuenta_mesa UNIQUE (cuenta_id, mesa_id),
    CONSTRAINT chk_cuenta_mesa_vigencia CHECK (
        (activa = TRUE AND desvinculada_en IS NULL)
        OR (activa = FALSE AND desvinculada_en IS NOT NULL)
    ),
    CONSTRAINT fk_cuenta_mesa_cuenta
        FOREIGN KEY (cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_cuenta_mesa_mesa
        FOREIGN KEY (mesa_id) REFERENCES mesas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_cuenta_mesa_origen
        FOREIGN KEY (origen_cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_cuenta_mesa_activa
    ON cuenta_mesas (mesa_id)
    WHERE activa = TRUE;

CREATE INDEX idx_cuenta_mesas_cuenta_activas
    ON cuenta_mesas (cuenta_id, activa, es_principal);

CREATE TABLE historial_estados_mesa (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id             BIGINT NOT NULL,
    cuenta_id           BIGINT NULL,
    reserva_id          BIGINT NULL,
    estado_anterior     VARCHAR(20) NULL,
    estado_nuevo        VARCHAR(20) NOT NULL,
    usuario_id          BIGINT NULL,
    motivo              VARCHAR(255) NULL,
    cambiado_en         TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_historial_mesa_estado_anterior CHECK (
        estado_anterior IS NULL OR estado_anterior IN (
            'LIBRE', 'RESERVADA', 'OCUPADA', 'CUENTA_SOLICITADA'
        )
    ),
    CONSTRAINT chk_historial_mesa_estado_nuevo CHECK (
        estado_nuevo IN ('LIBRE', 'RESERVADA', 'OCUPADA', 'CUENTA_SOLICITADA')
    ),
    CONSTRAINT fk_historial_mesa
        FOREIGN KEY (mesa_id) REFERENCES mesas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_historial_mesa_cuenta
        FOREIGN KEY (cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_historial_mesa_reserva
        FOREIGN KEY (reserva_id) REFERENCES reservas(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_historial_mesa_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE INDEX idx_historial_mesa_reporte
    ON historial_estados_mesa (mesa_id, cambiado_en);

CREATE TABLE transferencias_cuenta (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id           BIGINT NOT NULL,
    mesa_origen_id      BIGINT NOT NULL,
    mesa_destino_id     BIGINT NOT NULL,
    realizada_por_id    BIGINT NOT NULL,
    motivo              VARCHAR(500) NULL,
    realizada_en        TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_transferencia_mesas CHECK (mesa_origen_id <> mesa_destino_id),
    CONSTRAINT fk_transferencia_cuenta
        FOREIGN KEY (cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transferencia_origen
        FOREIGN KEY (mesa_origen_id) REFERENCES mesas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transferencia_destino
        FOREIGN KEY (mesa_destino_id) REFERENCES mesas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transferencia_usuario
        FOREIGN KEY (realizada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE fusiones_cuenta (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_origen_id        BIGINT NOT NULL,
    cuenta_destino_id       BIGINT NOT NULL,
    realizada_por_id        BIGINT NOT NULL,
    motivo                  VARCHAR(500) NULL,
    realizada_en            TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fusion_cuenta_origen UNIQUE (cuenta_origen_id),
    CONSTRAINT chk_fusion_cuentas CHECK (cuenta_origen_id <> cuenta_destino_id),
    CONSTRAINT fk_fusion_origen
        FOREIGN KEY (cuenta_origen_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_fusion_destino
        FOREIGN KEY (cuenta_destino_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_fusion_usuario
        FOREIGN KEY (realizada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE subcuentas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id           BIGINT NOT NULL,
    numero_subcuenta    SMALLINT NOT NULL,
    nombre              VARCHAR(100) NULL,
    tipo_division       VARCHAR(15) NOT NULL,
    porcentaje_asignado DECIMAL(7,4) NULL,
    estado              VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
    subtotal_snapshot   DECIMAL(12,2) NOT NULL DEFAULT 0,
    creado_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subcuenta_numero UNIQUE (cuenta_id, numero_subcuenta),
    CONSTRAINT chk_subcuenta_numero CHECK (numero_subcuenta > 0),
    CONSTRAINT chk_subcuenta_tipo CHECK (
        tipo_division IN ('PERSONAS', 'ITEMS')
    ),
    CONSTRAINT chk_subcuenta_porcentaje CHECK (
        (tipo_division = 'ITEMS' AND porcentaje_asignado IS NULL)
        OR (
            tipo_division = 'PERSONAS'
            AND porcentaje_asignado > 0
            AND porcentaje_asignado <= 100
        )
    ),
    CONSTRAINT chk_subcuenta_estado CHECK (
        estado IN ('PENDIENTE', 'FACTURADA', 'CANCELADA')
    ),
    CONSTRAINT chk_subcuenta_subtotal CHECK (subtotal_snapshot >= 0),
    CONSTRAINT fk_subcuenta_cuenta
        FOREIGN KEY (cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE comandas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id           BIGINT NOT NULL,
    numero_ronda        SMALLINT NOT NULL,
    mesero_id           BIGINT NOT NULL,
    estado              VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    creada_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enviada_en          TIMESTAMPTZ(6) NULL,
    finalizada_en       TIMESTAMPTZ(6) NULL,
    notas_generales     VARCHAR(500) NULL,
    CONSTRAINT uq_comanda_ronda UNIQUE (cuenta_id, numero_ronda),
    CONSTRAINT chk_comanda_numero_ronda CHECK (numero_ronda > 0),
    CONSTRAINT chk_comanda_estado CHECK (
        estado IN (
            'BORRADOR', 'RECIBIDA', 'EN_PREPARACION',
            'LISTA', 'ENTREGADA', 'CANCELADA'
        )
    ),
    CONSTRAINT chk_comanda_fechas_estado CHECK (
        (estado = 'BORRADOR'
            AND enviada_en IS NULL
            AND finalizada_en IS NULL)
        OR (estado IN ('RECIBIDA', 'EN_PREPARACION', 'LISTA')
            AND enviada_en IS NOT NULL
            AND finalizada_en IS NULL)
        OR (estado IN ('ENTREGADA', 'CANCELADA')
            AND enviada_en IS NOT NULL
            AND finalizada_en IS NOT NULL)
    ),
    CONSTRAINT fk_comanda_cuenta
        FOREIGN KEY (cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_comanda_mesero
        FOREIGN KEY (mesero_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_comandas_cocina
    ON comandas (estado, enviada_en);

-- Cada renglon representa un platillo o un combo. Se guardan snapshots para que
-- cambios futuros de nombre, precio, receta o tiempo no alteren la venta historica.
CREATE TABLE comanda_detalles (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_id                  BIGINT NOT NULL,
    platillo_id                 BIGINT NULL,
    combo_id                    BIGINT NULL,
    receta_version_id           BIGINT NULL,
    nombre_snapshot             VARCHAR(150) NOT NULL,
    cantidad                    SMALLINT NOT NULL,
    precio_unitario_snapshot    DECIMAL(12,2) NOT NULL,
    costo_unitario_snapshot     DECIMAL(14,4) NOT NULL DEFAULT 0,
    tiempo_estimado_minutos     SMALLINT NOT NULL,
    notas_especiales            VARCHAR(500) NULL,
    estado                      VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    recibido_en                 TIMESTAMPTZ(6) NULL,
    preparacion_iniciada_en     TIMESTAMPTZ(6) NULL,
    listo_en                    TIMESTAMPTZ(6) NULL,
    entregado_en                TIMESTAMPTZ(6) NULL,
    actualizado_por_id          BIGINT NULL,
    actualizado_en              TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_comanda_detalle_producto CHECK (
        (platillo_id IS NOT NULL AND combo_id IS NULL)
        OR (platillo_id IS NULL AND combo_id IS NOT NULL)
    ),
    CONSTRAINT chk_comanda_detalle_receta CHECK (
        (platillo_id IS NOT NULL
            AND combo_id IS NULL
            AND receta_version_id IS NOT NULL)
        OR (platillo_id IS NULL
            AND combo_id IS NOT NULL
            AND receta_version_id IS NULL)
    ),
    CONSTRAINT chk_comanda_detalle_valores CHECK (
        cantidad > 0
        AND precio_unitario_snapshot >= 0
        AND costo_unitario_snapshot >= 0
        AND tiempo_estimado_minutos > 0
    ),
    CONSTRAINT chk_comanda_detalle_estado CHECK (
        estado IN (
            'BORRADOR', 'RECIBIDO', 'EN_PREPARACION', 'LISTO',
            'ENTREGADO', 'NO_DISPONIBLE', 'CANCELADO'
        )
    ),
    CONSTRAINT chk_comanda_detalle_fechas CHECK (
        (estado = 'BORRADOR'
            AND recibido_en IS NULL
            AND preparacion_iniciada_en IS NULL
            AND listo_en IS NULL
            AND entregado_en IS NULL)
        OR (estado IN ('RECIBIDO', 'NO_DISPONIBLE', 'CANCELADO')
            AND recibido_en IS NOT NULL)
        OR (estado = 'EN_PREPARACION'
            AND recibido_en IS NOT NULL
            AND preparacion_iniciada_en IS NOT NULL)
        OR (estado = 'LISTO'
            AND recibido_en IS NOT NULL
            AND preparacion_iniciada_en IS NOT NULL
            AND listo_en IS NOT NULL)
        OR (estado = 'ENTREGADO'
            AND recibido_en IS NOT NULL
            AND preparacion_iniciada_en IS NOT NULL
            AND listo_en IS NOT NULL
            AND entregado_en IS NOT NULL)
    ),
    CONSTRAINT fk_comanda_detalle_comanda
        FOREIGN KEY (comanda_id) REFERENCES comandas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_comanda_detalle_platillo
        FOREIGN KEY (platillo_id) REFERENCES platillos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_comanda_detalle_combo
        FOREIGN KEY (combo_id) REFERENCES combos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_comanda_detalle_receta
        FOREIGN KEY (receta_version_id) REFERENCES receta_versiones(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_comanda_detalle_usuario
        FOREIGN KEY (actualizado_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE INDEX idx_comanda_detalles_cocina
    ON comanda_detalles (estado, recibido_en);
CREATE INDEX idx_comanda_detalles_comanda
    ON comanda_detalles (comanda_id, estado);

-- Congela los componentes y versiones de receta de un combo cuando se agrega
-- a una comanda. Asi una edicion posterior del combo o de sus recetas no cambia
-- el costo ni los insumos que se descontaran para esa orden ya capturada.
CREATE TABLE comanda_detalle_combo_recetas (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_detalle_id          BIGINT NOT NULL,
    platillo_id                 BIGINT NOT NULL,
    receta_version_id           BIGINT NOT NULL,
    cantidad_platillo           SMALLINT NOT NULL,
    costo_unitario_snapshot     DECIMAL(14,4) NOT NULL,
    CONSTRAINT uq_comanda_combo_receta
        UNIQUE (comanda_detalle_id, platillo_id),
    CONSTRAINT chk_comanda_combo_receta_valores CHECK (
        cantidad_platillo > 0 AND costo_unitario_snapshot >= 0
    ),
    CONSTRAINT fk_comanda_combo_receta_detalle
        FOREIGN KEY (comanda_detalle_id) REFERENCES comanda_detalles(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_comanda_combo_receta_platillo
        FOREIGN KEY (platillo_id) REFERENCES platillos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_comanda_combo_receta_version
        FOREIGN KEY (receta_version_id) REFERENCES receta_versiones(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_comanda_combo_receta_version
    ON comanda_detalle_combo_recetas (receta_version_id);

CREATE TABLE comanda_detalle_modificadores (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_detalle_id              BIGINT NOT NULL,
    modificador_id                  BIGINT NOT NULL,
    receta_modificador_version_id   BIGINT NULL,
    nombre_snapshot                 VARCHAR(120) NOT NULL,
    cantidad                        SMALLINT NOT NULL DEFAULT 1,
    precio_adicional_snapshot       DECIMAL(12,2) NOT NULL DEFAULT 0,
    costo_adicional_snapshot        DECIMAL(14,4) NOT NULL DEFAULT 0,
    CONSTRAINT uq_comanda_detalle_modificador
        UNIQUE (comanda_detalle_id, modificador_id),
    CONSTRAINT chk_comanda_modificador_valores CHECK (
        cantidad > 0
        AND precio_adicional_snapshot >= 0
    ),
    CONSTRAINT fk_comanda_mod_detalle
        FOREIGN KEY (comanda_detalle_id) REFERENCES comanda_detalles(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_comanda_mod_modificador
        FOREIGN KEY (modificador_id) REFERENCES modificadores(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_comanda_mod_receta
        FOREIGN KEY (receta_modificador_version_id)
        REFERENCES receta_modificador_versiones(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE subcuenta_detalles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcuenta_id        BIGINT NOT NULL,
    comanda_detalle_id  BIGINT NOT NULL,
    cantidad_asignada   DECIMAL(12,6) NOT NULL,
    CONSTRAINT uq_subcuenta_detalle
        UNIQUE (subcuenta_id, comanda_detalle_id),
    CONSTRAINT chk_subcuenta_detalle_cantidad CHECK (cantidad_asignada > 0),
    CONSTRAINT fk_subcuenta_detalle_subcuenta
        FOREIGN KEY (subcuenta_id) REFERENCES subcuentas(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_subcuenta_detalle_comanda
        FOREIGN KEY (comanda_detalle_id) REFERENCES comanda_detalles(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- Registra cancelaciones normales, excepciones autorizadas y faltantes reales
-- detectados por cocina. La accion de inventario queda trazable.
CREATE TABLE cancelaciones_comanda_detalle (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_detalle_id      BIGINT NOT NULL,
    tipo                    VARCHAR(30) NOT NULL,
    motivo                  VARCHAR(500) NOT NULL,
    estado_solicitud        VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
    accion_inventario       VARCHAR(25) NOT NULL DEFAULT 'SIN_AJUSTE',
    solicitada_por_id       BIGINT NOT NULL,
    autorizada_por_id       BIGINT NULL,
    solicitada_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resuelta_en             TIMESTAMPTZ(6) NULL,
    CONSTRAINT uq_cancelacion_detalle UNIQUE (comanda_detalle_id),
    CONSTRAINT chk_cancelacion_tipo CHECK (
        tipo IN ('CLIENTE', 'ERROR_MESERO', 'NO_DISPONIBLE_COCINA', 'OTRO')
    ),
    CONSTRAINT chk_cancelacion_estado CHECK (
        estado_solicitud IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')
    ),
    CONSTRAINT chk_cancelacion_inventario CHECK (
        accion_inventario IN ('REINTEGRAR', 'REGISTRAR_MERMA', 'SIN_AJUSTE')
    ),
    CONSTRAINT chk_cancelacion_resolucion CHECK (
        (estado_solicitud = 'PENDIENTE'
            AND autorizada_por_id IS NULL
            AND resuelta_en IS NULL)
        OR (estado_solicitud IN ('APROBADA', 'RECHAZADA')
            AND autorizada_por_id IS NOT NULL
            AND resuelta_en IS NOT NULL
            AND resuelta_en >= solicitada_en)
    ),
    CONSTRAINT chk_cancelacion_accion_estado CHECK (
        estado_solicitud = 'APROBADA'
        OR accion_inventario = 'SIN_AJUSTE'
    ),
    CONSTRAINT fk_cancelacion_detalle
        FOREIGN KEY (comanda_detalle_id) REFERENCES comanda_detalles(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_cancelacion_solicitante
        FOREIGN KEY (solicitada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_cancelacion_autorizador
        FOREIGN KEY (autorizada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

-- ============================================================================
-- 6. ENTRADAS, MERMAS Y KARDEX DE INVENTARIO
-- ============================================================================

CREATE TABLE entradas_inventario (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id      BIGINT NOT NULL,
    numero_documento    VARCHAR(40) NOT NULL,
    fecha_recepcion     TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    proveedor_nombre    VARCHAR(150) NULL,
    referencia_compra   VARCHAR(100) NULL,
    observaciones       VARCHAR(500) NULL,
    recibida_por_id     BIGINT NOT NULL,
    creado_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_entrada_documento UNIQUE (restaurante_id, numero_documento),
    CONSTRAINT fk_entrada_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_entrada_usuario
        FOREIGN KEY (recibida_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE entrada_inventario_detalles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrada_id          BIGINT NOT NULL,
    insumo_id           BIGINT NOT NULL,
    cantidad            DECIMAL(18,4) NOT NULL,
    costo_unitario      DECIMAL(14,4) NOT NULL,
    costo_total         DECIMAL(18,4) GENERATED ALWAYS AS
                        (ROUND(cantidad * costo_unitario, 4)) STORED,
    lote                VARCHAR(80) NULL,
    fecha_vencimiento   DATE NULL,
    CONSTRAINT uq_entrada_detalle_insumo_lote
        UNIQUE (entrada_id, insumo_id, lote),
    CONSTRAINT chk_entrada_detalle_valores CHECK (
        cantidad > 0 AND costo_unitario >= 0
    ),
    CONSTRAINT fk_entrada_detalle_entrada
        FOREIGN KEY (entrada_id) REFERENCES entradas_inventario(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_entrada_detalle_insumo
        FOREIGN KEY (insumo_id) REFERENCES insumos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE mermas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id      BIGINT NOT NULL,
    numero_documento    VARCHAR(40) NOT NULL,
    tipo_motivo         VARCHAR(20) NOT NULL,
    motivo_general      VARCHAR(500) NOT NULL,
    registrada_por_id   BIGINT NOT NULL,
    registrada_en       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_merma_documento UNIQUE (restaurante_id, numero_documento),
    CONSTRAINT chk_merma_motivo CHECK (
        tipo_motivo IN ('VENCIMIENTO', 'DANO', 'ERROR_MANEJO', 'OTRO')
    ),
    CONSTRAINT fk_merma_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_merma_usuario
        FOREIGN KEY (registrada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE merma_detalles (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merma_id                BIGINT NOT NULL,
    insumo_id               BIGINT NOT NULL,
    cantidad                DECIMAL(18,4) NOT NULL,
    costo_unitario_snapshot DECIMAL(14,4) NOT NULL,
    costo_total             DECIMAL(18,4) GENERATED ALWAYS AS
                            (ROUND(cantidad * costo_unitario_snapshot, 4)) STORED,
    lote                    VARCHAR(80) NULL,
    observacion             VARCHAR(255) NULL,
    CONSTRAINT uq_merma_detalle_insumo_lote
        UNIQUE (merma_id, insumo_id, lote),
    CONSTRAINT chk_merma_detalle_valores CHECK (
        cantidad > 0 AND costo_unitario_snapshot >= 0
    ),
    CONSTRAINT fk_merma_detalle_merma
        FOREIGN KEY (merma_id) REFERENCES mermas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_merma_detalle_insumo
        FOREIGN KEY (insumo_id) REFERENCES insumos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- Todas las cantidades del kardex se guardan en la unidad de stock del insumo.
CREATE TABLE movimientos_inventario (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id                  BIGINT NOT NULL,
    insumo_id                       BIGINT NOT NULL,
    tipo                            VARCHAR(30) NOT NULL,
    cantidad                        DECIMAL(18,4) NOT NULL,
    stock_anterior                  DECIMAL(18,4) NULL,
    stock_resultante                DECIMAL(18,4) NULL,
    costo_unitario_snapshot         DECIMAL(14,4) NULL,
    costo_total_snapshot            DECIMAL(18,4) GENERATED ALWAYS AS
                                    (ROUND(cantidad * costo_unitario_snapshot, 4)) STORED,
    entrada_detalle_id              BIGINT NULL,
    merma_detalle_id                BIGINT NULL,
    comanda_detalle_id              BIGINT NULL,
    cancelacion_comanda_detalle_id  BIGINT NULL,
    motivo                          VARCHAR(500) NOT NULL,
    usuario_responsable_id          BIGINT NOT NULL,
    creado_en                       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_movimiento_entrada_detalle UNIQUE (entrada_detalle_id),
    CONSTRAINT uq_movimiento_merma_detalle UNIQUE (merma_detalle_id),
    CONSTRAINT chk_movimiento_tipo CHECK (
        tipo IN (
            'ENTRADA_COMPRA', 'SALIDA_VENTA', 'SALIDA_MERMA',
            'AJUSTE_ENTRADA', 'AJUSTE_SALIDA', 'REINTEGRO_CANCELACION'
        )
    ),
    CONSTRAINT chk_movimiento_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_movimiento_stock CHECK (
        stock_anterior IS NULL OR stock_anterior >= 0
    ),
    CONSTRAINT chk_movimiento_resultante CHECK (
        stock_resultante IS NULL OR stock_resultante >= 0
    ),
    CONSTRAINT chk_movimiento_origen CHECK (
        (
            tipo = 'ENTRADA_COMPRA'
            AND entrada_detalle_id IS NOT NULL
            AND num_nonnulls(
                entrada_detalle_id, merma_detalle_id,
                comanda_detalle_id, cancelacion_comanda_detalle_id
            ) = 1
        )
        OR (
            tipo = 'SALIDA_MERMA'
            AND merma_detalle_id IS NOT NULL
            AND num_nonnulls(
                entrada_detalle_id, merma_detalle_id,
                comanda_detalle_id, cancelacion_comanda_detalle_id
            ) = 1
        )
        OR (
            tipo = 'SALIDA_VENTA'
            AND comanda_detalle_id IS NOT NULL
            AND num_nonnulls(
                entrada_detalle_id, merma_detalle_id,
                comanda_detalle_id, cancelacion_comanda_detalle_id
            ) = 1
        )
        OR (
            tipo = 'REINTEGRO_CANCELACION'
            AND cancelacion_comanda_detalle_id IS NOT NULL
            AND num_nonnulls(
                entrada_detalle_id, merma_detalle_id,
                comanda_detalle_id, cancelacion_comanda_detalle_id
            ) = 1
        )
        OR (
            tipo IN ('AJUSTE_ENTRADA', 'AJUSTE_SALIDA')
            AND num_nonnulls(
                entrada_detalle_id, merma_detalle_id,
                comanda_detalle_id, cancelacion_comanda_detalle_id
            ) = 0
        )
    ),
    CONSTRAINT fk_movimiento_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_insumo
        FOREIGN KEY (insumo_id) REFERENCES insumos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_entrada_detalle
        FOREIGN KEY (entrada_detalle_id) REFERENCES entrada_inventario_detalles(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_merma_detalle
        FOREIGN KEY (merma_detalle_id) REFERENCES merma_detalles(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_comanda_detalle
        FOREIGN KEY (comanda_detalle_id) REFERENCES comanda_detalles(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_cancelacion
        FOREIGN KEY (cancelacion_comanda_detalle_id)
        REFERENCES cancelaciones_comanda_detalle(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_usuario
        FOREIGN KEY (usuario_responsable_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_kardex_insumo_fecha
    ON movimientos_inventario (insumo_id, creado_en);
CREATE INDEX idx_kardex_tipo_fecha
    ON movimientos_inventario (restaurante_id, tipo, creado_en);
CREATE INDEX idx_kardex_comanda
    ON movimientos_inventario (comanda_detalle_id);
CREATE INDEX idx_kardex_cancelacion
    ON movimientos_inventario (cancelacion_comanda_detalle_id);

CREATE UNIQUE INDEX uq_kardex_venta_insumo_detalle
    ON movimientos_inventario (comanda_detalle_id, insumo_id)
    WHERE tipo = 'SALIDA_VENTA';

CREATE UNIQUE INDEX uq_kardex_reintegro_insumo_cancelacion
    ON movimientos_inventario (cancelacion_comanda_detalle_id, insumo_id)
    WHERE tipo = 'REINTEGRO_CANCELACION';

-- ============================================================================

-- Indices para las claves foraneas que no quedan cubiertas por otro indice.
CREATE INDEX idx_fk_cuenta_cliente
    ON cuentas (cliente_id);
CREATE INDEX idx_fk_cuenta_mesa_mesa
    ON cuenta_mesas (mesa_id);
CREATE INDEX idx_fk_cuenta_mesa_origen
    ON cuenta_mesas (origen_cuenta_id);
CREATE INDEX idx_fk_historial_mesa_cuenta
    ON historial_estados_mesa (cuenta_id);
CREATE INDEX idx_fk_historial_mesa_reserva
    ON historial_estados_mesa (reserva_id);
CREATE INDEX idx_fk_historial_mesa_usuario
    ON historial_estados_mesa (usuario_id);
CREATE INDEX idx_fk_transferencia_cuenta
    ON transferencias_cuenta (cuenta_id);
CREATE INDEX idx_fk_transferencia_origen
    ON transferencias_cuenta (mesa_origen_id);
CREATE INDEX idx_fk_transferencia_destino
    ON transferencias_cuenta (mesa_destino_id);
CREATE INDEX idx_fk_transferencia_usuario
    ON transferencias_cuenta (realizada_por_id);
CREATE INDEX idx_fk_fusion_destino
    ON fusiones_cuenta (cuenta_destino_id);
CREATE INDEX idx_fk_fusion_usuario
    ON fusiones_cuenta (realizada_por_id);
CREATE INDEX idx_fk_comanda_mesero
    ON comandas (mesero_id);
CREATE INDEX idx_fk_comanda_detalle_platillo
    ON comanda_detalles (platillo_id);
CREATE INDEX idx_fk_comanda_detalle_combo
    ON comanda_detalles (combo_id);
CREATE INDEX idx_fk_comanda_detalle_receta
    ON comanda_detalles (receta_version_id);
CREATE INDEX idx_fk_comanda_detalle_usuario
    ON comanda_detalles (actualizado_por_id);
CREATE INDEX idx_fk_comanda_combo_receta_platillo
    ON comanda_detalle_combo_recetas (platillo_id);
CREATE INDEX idx_fk_comanda_mod_modificador
    ON comanda_detalle_modificadores (modificador_id);
CREATE INDEX idx_fk_comanda_mod_receta
    ON comanda_detalle_modificadores (receta_modificador_version_id);
CREATE INDEX idx_fk_subcuenta_detalle_comanda
    ON subcuenta_detalles (comanda_detalle_id);
CREATE INDEX idx_fk_cancelacion_solicitante
    ON cancelaciones_comanda_detalle (solicitada_por_id);
CREATE INDEX idx_fk_cancelacion_autorizador
    ON cancelaciones_comanda_detalle (autorizada_por_id);
CREATE INDEX idx_fk_entrada_usuario
    ON entradas_inventario (recibida_por_id);
CREATE INDEX idx_fk_entrada_detalle_insumo
    ON entrada_inventario_detalles (insumo_id);
CREATE INDEX idx_fk_merma_usuario
    ON mermas (registrada_por_id);
CREATE INDEX idx_fk_merma_detalle_insumo
    ON merma_detalles (insumo_id);
CREATE INDEX idx_fk_movimiento_usuario
    ON movimientos_inventario (usuario_responsable_id);
