
SET search_path TO restaurante, public;
SET TIME ZONE 'UTC';

CREATE TABLE cajas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT NOT NULL,
    codigo          VARCHAR(30) NOT NULL,
    nombre          VARCHAR(100) NOT NULL,
    ubicacion       VARCHAR(150) NULL,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_caja_codigo UNIQUE (restaurante_id, codigo),
    CONSTRAINT uq_caja_nombre UNIQUE (restaurante_id, nombre),
    CONSTRAINT fk_caja_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE turnos_caja (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_id                     BIGINT NOT NULL,
    cajero_id                   BIGINT NOT NULL,
    estado                      VARCHAR(10) NOT NULL DEFAULT 'ABIERTA',
    monto_inicial_efectivo      DECIMAL(12,2) NOT NULL,
    abierta_en                  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    efectivo_esperado_cierre    DECIMAL(12,2) NULL,
    efectivo_real_cierre        DECIMAL(12,2) NULL,
    diferencia_cierre           DECIMAL(12,2) NULL,
    observaciones_apertura      VARCHAR(500) NULL,
    observaciones_cierre        VARCHAR(500) NULL,
    cerrada_en                  TIMESTAMPTZ(6) NULL,
    CONSTRAINT chk_turno_estado CHECK (estado IN ('ABIERTA', 'CERRADA')),
    CONSTRAINT chk_turno_montos CHECK (
        monto_inicial_efectivo >= 0
        AND (efectivo_esperado_cierre IS NULL OR efectivo_esperado_cierre >= 0)
        AND (efectivo_real_cierre IS NULL OR efectivo_real_cierre >= 0)
    ),
    CONSTRAINT chk_turno_cierre CHECK (
        (estado = 'ABIERTA'
            AND cerrada_en IS NULL
            AND efectivo_esperado_cierre IS NULL
            AND efectivo_real_cierre IS NULL
            AND diferencia_cierre IS NULL)
        OR (estado = 'CERRADA'
            AND cerrada_en IS NOT NULL
            AND efectivo_esperado_cierre IS NOT NULL
            AND efectivo_real_cierre IS NOT NULL
            AND diferencia_cierre = ROUND(
                efectivo_real_cierre - efectivo_esperado_cierre,
                2
            ))
    ),
    CONSTRAINT fk_turno_caja
        FOREIGN KEY (caja_id) REFERENCES cajas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_turno_cajero
        FOREIGN KEY (cajero_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_turno_caja_abierta
    ON turnos_caja (caja_id)
    WHERE estado = 'ABIERTA';

CREATE UNIQUE INDEX uq_turno_cajero_abierto
    ON turnos_caja (cajero_id)
    WHERE estado = 'ABIERTA';

CREATE INDEX idx_turnos_caja_historial
    ON turnos_caja (caja_id, abierta_en, cerrada_en);
CREATE INDEX idx_turnos_cajero_historial
    ON turnos_caja (cajero_id, abierta_en);

CREATE TABLE metodos_pago (
    id                  SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(20) NOT NULL,
    nombre              VARCHAR(60) NOT NULL,
    afecta_efectivo     BOOLEAN NOT NULL DEFAULT FALSE,
    requiere_referencia BOOLEAN NOT NULL DEFAULT FALSE,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_metodo_pago_codigo UNIQUE (codigo),
    CONSTRAINT uq_metodo_pago_nombre UNIQUE (nombre)
);

CREATE TABLE secuencias_facturacion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id      BIGINT NOT NULL,
    tipo_documento      VARCHAR(20) NOT NULL DEFAULT 'COMPROBANTE',
    serie               VARCHAR(20) NOT NULL,
    ultimo_numero       BIGINT NOT NULL DEFAULT 0,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    actualizado_en      TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_secuencia_documento
        UNIQUE (restaurante_id, tipo_documento, serie),
    CONSTRAINT chk_secuencia_tipo CHECK (
        tipo_documento IN ('FACTURA', 'COMPROBANTE')
    ),
    CONSTRAINT fk_secuencia_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE facturas (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id              BIGINT NOT NULL,
    cuenta_id                   BIGINT NOT NULL,
    subcuenta_id                BIGINT NULL,
    turno_caja_id               BIGINT NOT NULL,
    configuracion_id            BIGINT NOT NULL,
    cliente_id                  BIGINT NULL,
    mesero_id                   BIGINT NOT NULL,
    cajero_id                   BIGINT NOT NULL,
    tipo_documento              VARCHAR(20) NOT NULL DEFAULT 'COMPROBANTE',
    serie                       VARCHAR(20) NOT NULL,
    numero_correlativo          BIGINT NOT NULL,
    numero_documento            VARCHAR(50) NOT NULL,
    estado                      VARCHAR(15) NOT NULL DEFAULT 'EMITIDA',
    subtotal                    DECIMAL(12,2) NOT NULL,
    descuento_total             DECIMAL(12,2) NOT NULL DEFAULT 0,
    descuento_puntos            DECIMAL(12,2) NOT NULL DEFAULT 0,
    porcentaje_impuesto         DECIMAL(7,4) NOT NULL,
    monto_impuesto              DECIMAL(12,2) NOT NULL,
    porcentaje_propina          DECIMAL(7,4) NOT NULL,
    monto_propina               DECIMAL(12,2) NOT NULL,
    total                       DECIMAL(12,2) NOT NULL,
    puntos_redimidos            BIGINT NOT NULL DEFAULT 0,
    puntos_otorgados            BIGINT NOT NULL DEFAULT 0,
    emitida_en                  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    anulada_en                  TIMESTAMPTZ(6) NULL,
    anulada_por_id              BIGINT NULL,
    motivo_anulacion            VARCHAR(500) NULL,
    CONSTRAINT uq_factura_documento
        UNIQUE (restaurante_id, tipo_documento, serie, numero_correlativo),
    CONSTRAINT uq_factura_numero_documento
        UNIQUE (restaurante_id, numero_documento),
    CONSTRAINT chk_factura_tipo CHECK (
        tipo_documento IN ('FACTURA', 'COMPROBANTE')
    ),
    CONSTRAINT chk_factura_identificacion CHECK (
        numero_correlativo > 0
        AND NULLIF(BTRIM(serie), '') IS NOT NULL
        AND NULLIF(BTRIM(numero_documento), '') IS NOT NULL
    ),
    CONSTRAINT chk_factura_estado CHECK (
        estado IN ('EMITIDA', 'ANULADA')
    ),
    CONSTRAINT chk_factura_montos CHECK (
        subtotal >= 0
        AND descuento_total >= 0
        AND descuento_total <= subtotal
        AND descuento_puntos >= 0
        AND descuento_puntos <= descuento_total
        AND porcentaje_impuesto BETWEEN 0 AND 100
        AND monto_impuesto >= 0
        AND porcentaje_propina BETWEEN 0 AND 100
        AND monto_propina >= 0
        AND total >= 0
        AND puntos_redimidos >= 0
        AND puntos_otorgados >= 0
        AND total = ROUND(
            subtotal - descuento_total + monto_impuesto + monto_propina,
            2
        )
    ),
    CONSTRAINT chk_factura_cliente_puntos CHECK (
        cliente_id IS NOT NULL
        OR (
            puntos_redimidos = 0
            AND puntos_otorgados = 0
            AND descuento_puntos = 0
        )
    ),
    CONSTRAINT chk_factura_anulacion CHECK (
        (estado = 'EMITIDA' AND anulada_en IS NULL)
        OR (estado = 'ANULADA' AND anulada_en IS NOT NULL AND motivo_anulacion IS NOT NULL)
    ),
    CONSTRAINT fk_factura_restaurante
        FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_cuenta
        FOREIGN KEY (cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_subcuenta
        FOREIGN KEY (subcuenta_id) REFERENCES subcuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_turno
        FOREIGN KEY (turno_caja_id) REFERENCES turnos_caja(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_configuracion
        FOREIGN KEY (configuracion_id) REFERENCES configuraciones_restaurante(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_factura_mesero
        FOREIGN KEY (mesero_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_cajero
        FOREIGN KEY (cajero_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_anulada_por
        FOREIGN KEY (anulada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_factura_cuenta_completa_emitida
    ON facturas (cuenta_id)
    WHERE subcuenta_id IS NULL AND estado = 'EMITIDA';

CREATE UNIQUE INDEX uq_factura_subcuenta_emitida
    ON facturas (subcuenta_id)
    WHERE subcuenta_id IS NOT NULL AND estado = 'EMITIDA';

CREATE INDEX idx_facturas_fecha
    ON facturas (restaurante_id, emitida_en, estado);
CREATE INDEX idx_facturas_mesero_fecha
    ON facturas (mesero_id, emitida_en);
CREATE INDEX idx_facturas_cajero_fecha
    ON facturas (cajero_id, emitida_en);
CREATE INDEX idx_facturas_cliente_fecha
    ON facturas (cliente_id, emitida_en);

CREATE TABLE factura_detalles (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id                      BIGINT NOT NULL,
    comanda_detalle_id              BIGINT NOT NULL,
    platillo_id                     BIGINT NULL,
    combo_id                        BIGINT NULL,
    nombre_snapshot                 VARCHAR(150) NOT NULL,
    categoria_snapshot              VARCHAR(100) NULL,
    cantidad                        DECIMAL(12,6) NOT NULL,
    precio_unitario_snapshot        DECIMAL(12,2) NOT NULL,
    total_modificadores_snapshot    DECIMAL(12,2) NOT NULL DEFAULT 0,
    costo_unitario_snapshot         DECIMAL(14,4) NOT NULL DEFAULT 0,
    subtotal_linea                  DECIMAL(12,2) NOT NULL,
    CONSTRAINT uq_factura_comanda_detalle
        UNIQUE (factura_id, comanda_detalle_id),
    CONSTRAINT chk_factura_detalle_producto CHECK (
        (platillo_id IS NOT NULL AND combo_id IS NULL)
        OR (platillo_id IS NULL AND combo_id IS NOT NULL)
    ),
    CONSTRAINT chk_factura_detalle_valores CHECK (
        cantidad > 0
        AND precio_unitario_snapshot >= 0
        AND total_modificadores_snapshot >= 0
        AND costo_unitario_snapshot >= 0
        AND subtotal_linea = ROUND(
            cantidad * (
                precio_unitario_snapshot + total_modificadores_snapshot
            ),
            2
        )
    ),
    CONSTRAINT fk_factura_detalle_factura
        FOREIGN KEY (factura_id) REFERENCES facturas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_detalle_comanda
        FOREIGN KEY (comanda_detalle_id) REFERENCES comanda_detalles(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_detalle_platillo
        FOREIGN KEY (platillo_id) REFERENCES platillos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_detalle_combo
        FOREIGN KEY (combo_id) REFERENCES combos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_factura_detalles_reporte_producto
    ON factura_detalles (platillo_id, combo_id);

CREATE TABLE factura_detalle_modificadores (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_detalle_id          BIGINT NOT NULL,
    modificador_id              BIGINT NULL,
    nombre_snapshot             VARCHAR(120) NOT NULL,
    cantidad                    SMALLINT NOT NULL DEFAULT 1,
    precio_adicional_snapshot   DECIMAL(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_factura_detalle_modificador
        UNIQUE (factura_detalle_id, modificador_id),
    CONSTRAINT chk_factura_modificador_valores CHECK (
        cantidad > 0 AND precio_adicional_snapshot >= 0
    ),
    CONSTRAINT fk_factura_mod_detalle
        FOREIGN KEY (factura_detalle_id) REFERENCES factura_detalles(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_factura_mod_modificador
        FOREIGN KEY (modificador_id) REFERENCES modificadores(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE TABLE pagos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id              BIGINT NOT NULL,
    metodo_pago_id          SMALLINT NOT NULL,
    monto                   DECIMAL(12,2) NOT NULL,
    monto_recibido          DECIMAL(12,2) NULL,
    cambio_entregado        DECIMAL(12,2) NULL,
    referencia             VARCHAR(120) NULL,
    autorizacion           VARCHAR(120) NULL,
    registrado_por_id      BIGINT NOT NULL,
    pagado_en               TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_pago_monto CHECK (
        monto > 0
        AND (monto_recibido IS NULL OR monto_recibido >= monto)
        AND (cambio_entregado IS NULL OR cambio_entregado >= 0)
        AND (
            monto_recibido IS NULL
            OR cambio_entregado = ROUND(monto_recibido - monto, 2)
        )
    ),
    CONSTRAINT fk_pago_factura
        FOREIGN KEY (factura_id) REFERENCES facturas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_pago_metodo
        FOREIGN KEY (metodo_pago_id) REFERENCES metodos_pago(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_pago_usuario
        FOREIGN KEY (registrado_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_pagos_factura
    ON pagos (factura_id, pagado_en);

CREATE TABLE transacciones_caja (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_caja_id       BIGINT NOT NULL,
    factura_id          BIGINT NULL,
    pago_id             BIGINT NULL,
    tipo                VARCHAR(25) NOT NULL,
    monto               DECIMAL(12,2) NOT NULL DEFAULT 0,
    puntos              BIGINT NOT NULL DEFAULT 0,
    descripcion         VARCHAR(500) NOT NULL,
    registrada_por_id   BIGINT NOT NULL,
    registrada_en       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_transaccion_caja_tipo CHECK (
        tipo IN (
            'APERTURA', 'VENTA', 'PROPINA', 'REDENCION_PUNTOS',
            'AJUSTE', 'CIERRE'
        )
    ),
    CONSTRAINT chk_transaccion_caja_monto CHECK (monto >= 0),
    CONSTRAINT chk_transaccion_caja_puntos CHECK (puntos >= 0),
    CONSTRAINT chk_transaccion_caja_origen CHECK (
        (tipo IN ('APERTURA', 'CIERRE')
            AND factura_id IS NULL AND pago_id IS NULL)
        OR (tipo = 'VENTA'
            AND factura_id IS NOT NULL AND pago_id IS NOT NULL)
        OR (tipo IN ('PROPINA', 'REDENCION_PUNTOS')
            AND factura_id IS NOT NULL AND pago_id IS NULL)
        OR (tipo = 'AJUSTE' AND pago_id IS NULL)
    ),
    CONSTRAINT fk_transaccion_turno
        FOREIGN KEY (turno_caja_id) REFERENCES turnos_caja(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transaccion_factura
        FOREIGN KEY (factura_id) REFERENCES facturas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transaccion_pago
        FOREIGN KEY (pago_id) REFERENCES pagos(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transaccion_usuario
        FOREIGN KEY (registrada_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_transacciones_turno_fecha
    ON transacciones_caja (turno_caja_id, registrada_en);

CREATE UNIQUE INDEX uq_transaccion_caja_pago
    ON transacciones_caja (pago_id)
    WHERE pago_id IS NOT NULL;

CREATE UNIQUE INDEX uq_transaccion_caja_apertura
    ON transacciones_caja (turno_caja_id)
    WHERE tipo = 'APERTURA';

CREATE UNIQUE INDEX uq_transaccion_caja_cierre
    ON transacciones_caja (turno_caja_id)
    WHERE tipo = 'CIERRE';

CREATE UNIQUE INDEX uq_transaccion_caja_propina_factura
    ON transacciones_caja (factura_id)
    WHERE tipo = 'PROPINA';

CREATE UNIQUE INDEX uq_transaccion_caja_redencion_factura
    ON transacciones_caja (factura_id)
    WHERE tipo = 'REDENCION_PUNTOS';


CREATE TABLE movimientos_puntos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id          BIGINT NOT NULL,
    factura_id          BIGINT NULL,
    tipo                VARCHAR(20) NOT NULL,
    cantidad_puntos     BIGINT NOT NULL,
    saldo_anterior      BIGINT NULL,
    saldo_resultante    BIGINT NULL,
    valor_monetario     DECIMAL(12,2) NOT NULL DEFAULT 0,
    motivo              VARCHAR(500) NOT NULL,
    registrado_por_id   BIGINT NULL,
    creado_en           TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_movimiento_puntos_factura_tipo UNIQUE (factura_id, tipo),
    CONSTRAINT chk_movimiento_puntos_tipo CHECK (
        tipo IN ('OTORGAMIENTO', 'REDENCION', 'AJUSTE')
    ),
    CONSTRAINT chk_movimiento_puntos_signo CHECK (
        (tipo = 'OTORGAMIENTO' AND cantidad_puntos > 0)
        OR (tipo = 'REDENCION' AND cantidad_puntos < 0)
        OR (tipo = 'AJUSTE' AND cantidad_puntos <> 0)
    ),
    CONSTRAINT chk_movimiento_puntos_saldos CHECK (
        (saldo_anterior IS NULL OR saldo_anterior >= 0)
        AND (saldo_resultante IS NULL OR saldo_resultante >= 0)
        AND valor_monetario >= 0
    ),
    CONSTRAINT fk_movimiento_puntos_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_puntos_factura
        FOREIGN KEY (factura_id) REFERENCES facturas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_puntos_usuario
        FOREIGN KEY (registrado_por_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE INDEX idx_movimientos_puntos_cliente_fecha
    ON movimientos_puntos (cliente_id, creado_en);
CREATE INDEX idx_movimientos_puntos_reporte
    ON movimientos_puntos (tipo, creado_en);

CREATE TABLE calificaciones_servicio (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id      BIGINT NOT NULL,
    cuenta_id       BIGINT NOT NULL,
    cliente_id      BIGINT NULL,
    mesero_id       BIGINT NOT NULL,
    calificacion    SMALLINT NOT NULL,
    comentario      VARCHAR(500) NULL,
    creada_en       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_calificacion_factura UNIQUE (factura_id),
    CONSTRAINT uq_calificacion_cuenta UNIQUE (cuenta_id),
    CONSTRAINT chk_calificacion_rango CHECK (calificacion BETWEEN 1 AND 5),
    CONSTRAINT fk_calificacion_factura
        FOREIGN KEY (factura_id) REFERENCES facturas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_calificacion_cuenta
        FOREIGN KEY (cuenta_id) REFERENCES cuentas(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_calificacion_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_calificacion_mesero
        FOREIGN KEY (mesero_id) REFERENCES usuarios(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX idx_calificaciones_mesero_fecha
    ON calificaciones_servicio (mesero_id, creada_en);


CREATE INDEX idx_fk_factura_turno
    ON facturas (turno_caja_id);
CREATE INDEX idx_fk_factura_configuracion
    ON facturas (configuracion_id);
CREATE INDEX idx_fk_factura_anulada_por
    ON facturas (anulada_por_id);
CREATE INDEX idx_fk_factura_detalle_factura
    ON factura_detalles (factura_id);
CREATE INDEX idx_fk_factura_detalle_comanda
    ON factura_detalles (comanda_detalle_id);
CREATE INDEX idx_fk_factura_detalle_combo
    ON factura_detalles (combo_id);
CREATE INDEX idx_fk_factura_mod_detalle
    ON factura_detalle_modificadores (factura_detalle_id);
CREATE INDEX idx_fk_factura_mod_modificador
    ON factura_detalle_modificadores (modificador_id);
CREATE INDEX idx_fk_pago_metodo
    ON pagos (metodo_pago_id);
CREATE INDEX idx_fk_pago_usuario
    ON pagos (registrado_por_id);
CREATE INDEX idx_fk_transaccion_factura
    ON transacciones_caja (factura_id);
CREATE INDEX idx_fk_transaccion_pago
    ON transacciones_caja (pago_id);
CREATE INDEX idx_fk_transaccion_usuario
    ON transacciones_caja (registrada_por_id);
CREATE INDEX idx_fk_puntos_usuario
    ON movimientos_puntos (registrado_por_id);
CREATE INDEX idx_fk_calificacion_cuenta
    ON calificaciones_servicio (cuenta_id);
CREATE INDEX idx_fk_calificacion_cliente
    ON calificaciones_servicio (cliente_id);
